name: Docker Build CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the server Docker image
      run: docker build --file docker/server.Dockerfile --tag messaging-app:server .
    - name: Build the client Docker image
      run: docker build --file docker/client.Dockerfile --tag messaging-app:client .
